testing check_date and adding skipped_marker jobs

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -47,6 +47,16 @@ jobs:
           if-no-files-found: error
           retention-days: 7
 
+  skipped_marker:
+    needs: check_date
+    if: ${{ needs.check_date.outputs.should_run == 'false' }}
+    runs-on: windows-latest
+    steps:
+      - name: Mark as Skipped
+        run: |
+          echo "Main job was skipped. Failing this job to reflect that."
+          exit 78  # Special exit code that marks a step as "neutral" (used by GitHub)
+
   check_date:
     runs-on: windows-latest
     name: Check latest commit
@@ -54,15 +64,14 @@ jobs:
       should_run: ${{ steps.should_run.outputs.should_run }}
     steps:
       - uses: actions/checkout@v4
-        with:
-          path: trunk
+        # with:
+        #   path: trunk
       - name: Print latest_commit
         run: echo ${{ github.sha }}
 
       - id: should_run
         continue-on-error: true
         name: Check latest commit is less than a day
-        if: ${{ github.event_name == 'schedule' }}
         run: |
           test -z $(git rev-list  --after="24 hours"  ${{ github.sha }})
           echo "should_run=false" >> "$env:GITHUB_OUTPUT"
